#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(
  cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." >/dev/null 2>&1
  pwd
)"

MATRIX_DIR="${ROOT_DIR}/deploy/local/matrix"
COMPOSE_FILE="${MATRIX_DIR}/docker-compose.yml"
ENV_FILE="${MATRIX_DIR}/.env"
STATE_FILE="${MATRIX_DIR}/state.json"

SYNAPSE_CONTAINER_NAME="bibliotalk-synapse"
SYNAPSE_IMAGE="matrixdotorg/synapse:latest"

log() {
  echo "matrix-dev: $*" >&2
}

die() {
  log "ERROR: $*"
  exit 1
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

require_env() {
  local var="$1"
  if [[ -z "${!var:-}" ]]; then
    die "missing required env var ${var} in ${ENV_FILE}"
  fi
}

rand_hex() {
  local n_bytes="$1"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "${n_bytes}"
    return 0
  fi
  python3 - <<PY
import secrets
print(secrets.token_hex(${n_bytes}))
PY
}

ensure_env_file() {
  mkdir -p "${MATRIX_DIR}"

  if [[ -f "${ENV_FILE}" ]]; then
    # Backfill new vars for existing dev env files (idempotent).
    if ! grep -q '^ELEMENT_CALL_PORT=' "${ENV_FILE}"; then
      cat >>"${ENV_FILE}" <<'EOF'

# MatrixRTC (Element Call + LiveKit) local dev
ELEMENT_CALL_PORT=9011
WELL_KNOWN_PORT=80

# LiveKit SFU ports (host-exposed for browser clients)
LIVEKIT_PORT=7880
LIVEKIT_UDP_PORT=7881

# LiveKit auth (dev-only defaults; safe to change locally)
LIVEKIT_URL=http://livekit.localhost:7880
LIVEKIT_KEY=devkey
LIVEKIT_SECRET=devsecret
LIVEKIT_KEYS=devkey:devsecret
LIVEKIT_FULL_ACCESS_HOMESERVERS=localhost

# Fallback MatrixRTC focus URL (used by matrix_service when call events omit foci)
VOIP_LIVEKIT_SERVICE_URL=http://localhost/livekit/jwt
EOF
      log "updated ${ENV_FILE} with MatrixRTC defaults"
    fi
    return 0
  fi

  local as_token hs_token shared_secret admin_password
  as_token="$(rand_hex 16)"
  hs_token="$(rand_hex 16)"
  shared_secret="$(rand_hex 16)"
  admin_password="$(rand_hex 12)"

  cat >"${ENV_FILE}" <<EOF
# Generated by ./scripts/matrix-dev.sh
#
# This file is gitignored. Safe to edit locally.

# Synapse/Element
MATRIX_SERVER_NAME=localhost
SYNAPSE_PORT=8008
ELEMENT_PORT=8081
ELEMENT_CALL_PORT=9011
WELL_KNOWN_PORT=80

# LiveKit SFU (MatrixRTC)
LIVEKIT_PORT=7880
LIVEKIT_UDP_PORT=7881
LIVEKIT_URL=http://livekit.localhost:7880
LIVEKIT_KEY=devkey
LIVEKIT_SECRET=devsecret
LIVEKIT_KEYS=devkey:devsecret
LIVEKIT_FULL_ACCESS_HOMESERVERS=localhost

# Fallback MatrixRTC focus URL (used by matrix_service when call events omit foci)
VOIP_LIVEKIT_SERVICE_URL=http://localhost/livekit/jwt

# Optional: proxy overrides for Synapse containers.
# Some Docker installations inject global proxy env vars into every container;
# if they're invalid (e.g. `http://proxy-host:port`), Synapse will crash.
MATRIX_HTTP_PROXY=
MATRIX_HTTPS_PROXY=
MATRIX_NO_PROXY=localhost,127.0.0.1

# Synapse admin (used by this script for provisioning)
MATRIX_ADMIN_USER=admin
MATRIX_ADMIN_PASSWORD=${admin_password}

# Optional: for shared-secret registration workflows
MATRIX_REGISTRATION_SHARED_SECRET=${shared_secret}

# Appservice registration (Synapse <-> matrix_service)
MATRIX_APPSERVICE_URL=http://host.docker.internal:9009
MATRIX_SENDER_LOCALPART=bt_system
MATRIX_SPIRIT_USER_PREFIX=bt_
MATRIX_AS_TOKEN=${as_token}
MATRIX_HS_TOKEN=${hs_token}
EOF

  log "wrote ${ENV_FILE}"
}

load_env() {
  # shellcheck disable=SC1090
  set -a
  source "${ENV_FILE}"
  set +a
}

ensure_appservice_yaml() {
  mkdir -p "${MATRIX_DIR}/appservice"

  local out="${MATRIX_DIR}/appservice/bibliotalk.local.yaml"
  if [[ -f "${out}" ]]; then
    return 0
  fi

  cat >"${out}" <<EOF
id: bibliotalk
url: ${MATRIX_APPSERVICE_URL}
as_token: "${MATRIX_AS_TOKEN}"
hs_token: "${MATRIX_HS_TOKEN}"
sender_localpart: "${MATRIX_SENDER_LOCALPART}"
rate_limited: false

namespaces:
  users:
    - exclusive: true
      regex: "@${MATRIX_SPIRIT_USER_PREFIX}.*:${MATRIX_SERVER_NAME}"
  aliases:
    - exclusive: true
      regex: "#${MATRIX_SPIRIT_USER_PREFIX}.*:${MATRIX_SERVER_NAME}"
  rooms: []
EOF

  log "wrote ${out}"
}

ensure_synapse_generated_config() {
  mkdir -p "${MATRIX_DIR}/synapse/data"

  local cfg="${MATRIX_DIR}/synapse/data/homeserver.yaml"
  if [[ -f "${cfg}" ]]; then
    return 0
  fi

  log "generating Synapse config in ${MATRIX_DIR}/synapse/data"
  docker run --rm \
    -e "SYNAPSE_SERVER_NAME=${MATRIX_SERVER_NAME}" \
    -e "SYNAPSE_REPORT_STATS=no" \
    -v "${MATRIX_DIR}/synapse/data:/data" \
    "${SYNAPSE_IMAGE}" generate >/dev/null
}

ensure_synapse_local_overrides() {
  mkdir -p "${MATRIX_DIR}/synapse/data"

  local cfg="${MATRIX_DIR}/synapse/data/homeserver.local.yaml"
  if [[ -f "${cfg}" ]]; then
    return 0
  fi

  cat >"${cfg}" <<EOF
# Local-only overrides for Bibliotalk dev.
#
# This file is generated by ./scripts/matrix-dev.sh and is safe to delete/regenerate.
# It is layered on top of /data/homeserver.yaml via Synapse's multiple --config-path support.

registration_shared_secret: "${MATRIX_REGISTRATION_SHARED_SECRET}"

app_service_config_files:
  - /data/appservices/bibliotalk.local.yaml
EOF

  log "wrote ${cfg}"
}

ensure_element_config() {
  mkdir -p "${MATRIX_DIR}/element"

  local out="${MATRIX_DIR}/element/config.json"
  if [[ -f "${out}" ]]; then
    return 0
  fi

  cat >"${out}" <<EOF
{
  "default_server_config": {
    "m.homeserver": {
      "base_url": "http://localhost:${SYNAPSE_PORT}",
      "server_name": "${MATRIX_SERVER_NAME}"
    }
  },
  "disable_custom_urls": true,
  "disable_guests": true,
  "brand": "Bibliotalk (Local)",
  "default_theme": "dark"
}
EOF

  log "wrote ${out}"
}

ensure_element_call_config() {
  mkdir -p "${MATRIX_DIR}/element_call"

  local out="${MATRIX_DIR}/element_call/config.json"
  if [[ -f "${out}" ]]; then
    return 0
  fi

  cat >"${out}" <<EOF
{
  "default_server_config": {
    "m.homeserver": {
      "base_url": "http://localhost:${SYNAPSE_PORT}",
      "server_name": "${MATRIX_SERVER_NAME}"
    }
  },
  "disable_custom_urls": true,
  "disable_guests": true,
  "brand": "Bibliotalk Call (Local)",
  "default_theme": "dark"
}
EOF

  log "wrote ${out}"
}

compose() {
  (cd "${MATRIX_DIR}" && docker compose --env-file "${ENV_FILE}" -f "${COMPOSE_FILE}" "$@")
}

wait_for_synapse() {
  local url="http://localhost:${SYNAPSE_PORT}/_matrix/client/versions"
  local i
  for i in $(seq 1 60); do
    if curl -fsS "${url}" >/dev/null 2>&1; then
      return 0
    fi
    sleep 1
  done
  die "synapse did not become ready at ${url}"
}

ensure_admin_user() {
  # Creates (or ensures) an admin user exists (idempotent).
  #
  # Use `-k` so we always match the active runtime config (which may include
  # `homeserver.local.yaml` overrides).
  docker exec "${SYNAPSE_CONTAINER_NAME}" register_new_matrix_user \
    -k "${MATRIX_REGISTRATION_SHARED_SECRET}" \
    --exists-ok \
    "http://localhost:8008" \
    -u "${MATRIX_ADMIN_USER}" \
    -p "${MATRIX_ADMIN_PASSWORD}" \
    -a >/dev/null
}

matrix_login() {
  local url="http://localhost:${SYNAPSE_PORT}/_matrix/client/v3/login"
  local payload
  payload="$(cat <<JSON
{
  "type": "m.login.password",
  "identifier": { "type": "m.id.user", "user": "${MATRIX_ADMIN_USER}" },
  "password": "${MATRIX_ADMIN_PASSWORD}"
}
JSON
)"

  local response http_code
  response="$(curl -sS "${url}" \
    -H 'Content-Type: application/json' \
    -d "${payload}" \
    -w "\n%{http_code}")"
  http_code="$(printf '%s' "${response}" | tail -n 1)"
  if [[ "${http_code}" != "200" ]]; then
    log "login failed (HTTP ${http_code}):"
    printf '%s\n' "${response}" | sed '$d' >&2 || true
    die "cannot login as ${MATRIX_ADMIN_USER}"
  fi

  printf '%s' "${response}" | sed '$d' | python3 -c 'import json,sys; print(json.load(sys.stdin)["access_token"])'
}

urlencode() {
  python3 -c 'from urllib.parse import quote; import sys; print(quote(sys.argv[1], safe=""))' "$1"
}

read_state() {
  if [[ -f "${STATE_FILE}" ]]; then
    cat "${STATE_FILE}"
  else
    echo "{}"
  fi
}

write_state() {
  local json_text="$1"
  printf '%s\n' "${json_text}" >"${STATE_FILE}"
  log "wrote ${STATE_FILE}"
}

upsert_state_rooms() {
  local space_room_id="$1"
  local general_room_id="$2"

  python3 - "${STATE_FILE}" "${space_room_id}" "${general_room_id}" <<'PY'
import json
import sys
from pathlib import Path

state_path = Path(sys.argv[1])
space_room_id = sys.argv[2]
general_room_id = sys.argv[3]

if state_path.exists():
    state = json.loads(state_path.read_text(encoding="utf-8"))
else:
    state = {}

state["space_room_id"] = space_room_id
state["general_room_id"] = general_room_id

state_path.write_text(json.dumps(state, indent=2, sort_keys=True) + "\n", encoding="utf-8")
PY
  log "wrote ${STATE_FILE}"
}

ensure_room_by_alias() {
  local token="$1"
  local alias_localpart="$2"
  local name="$3"
  local is_space="$4" # "true"/"false"

  local alias="#${alias_localpart}:${MATRIX_SERVER_NAME}"
  local alias_enc
  alias_enc="$(urlencode "${alias}")"

  local create_payload
  if [[ "${is_space}" == "true" ]]; then
    create_payload="$(cat <<JSON
{
  "name": "${name}",
  "topic": "Bibliotalk dev space",
  "preset": "public_chat",
  "visibility": "public",
  "room_alias_name": "${alias_localpart}",
  "creation_content": { "type": "m.space" }
}
JSON
)"
  else
    create_payload="$(cat <<JSON
{
  "name": "${name}",
  "preset": "public_chat",
  "visibility": "public",
  "room_alias_name": "${alias_localpart}"
}
JSON
)"
  fi

  local create_url="http://localhost:${SYNAPSE_PORT}/_matrix/client/v3/createRoom"
  local response
  if response="$(curl -fsS "${create_url}" \
    -H "Authorization: Bearer ${token}" \
    -H 'Content-Type: application/json' \
    -d "${create_payload}" 2>/dev/null)"; then
    python3 -c 'import json,sys; print(json.loads(sys.stdin.read())["room_id"])' <<<"${response}"
    return 0
  fi

  # If create failed (often alias exists), resolve alias -> room_id.
  local dir_url="http://localhost:${SYNAPSE_PORT}/_matrix/client/v3/directory/room/${alias_enc}"
  curl -fsS "${dir_url}" -H "Authorization: Bearer ${token}" | python3 - <<'PY'
import json, sys
print(json.load(sys.stdin)["room_id"])
PY
}

ensure_space_and_general_room() {
  local token="$1"

  local space_room_id general_room_id
  space_room_id="$(ensure_room_by_alias "${token}" "bibliotalk-space" "Bibliotalk" "true")"
  general_room_id="$(ensure_room_by_alias "${token}" "bibliotalk-general" "General" "false")"

  # Link `General` under the space.
  local child_url="http://localhost:${SYNAPSE_PORT}/_matrix/client/v3/rooms/${space_room_id}/state/m.space.child/${general_room_id}"
  curl -fsS -X PUT "${child_url}" \
    -H "Authorization: Bearer ${token}" \
    -H 'Content-Type: application/json' \
    -d "$(cat <<JSON
{ "via": ["${MATRIX_SERVER_NAME}"], "suggested": true }
JSON
)" >/dev/null

  upsert_state_rooms "${space_room_id}" "${general_room_id}"

  log "space: ${space_room_id} (alias #bibliotalk-space:${MATRIX_SERVER_NAME})"
  log "room : ${general_room_id} (alias #bibliotalk-general:${MATRIX_SERVER_NAME})"
}

cmd_init() {
  require_cmd docker
  require_cmd curl
  require_cmd python3

  ensure_env_file
  load_env
  ensure_appservice_yaml
  ensure_element_config
  ensure_element_call_config

  log "init complete"
}

cmd_up() {
  cmd_init

  require_env MATRIX_SERVER_NAME
  require_env MATRIX_REGISTRATION_SHARED_SECRET

  ensure_synapse_generated_config
  ensure_synapse_local_overrides

  compose up -d synapse >/dev/null

  wait_for_synapse

  compose up -d element element-call livekit lk-jwt-service well-known >/dev/null

  log "synapse: http://localhost:${SYNAPSE_PORT}"
  log "element : http://localhost:${ELEMENT_PORT}"
  log "call   : http://localhost:${ELEMENT_CALL_PORT}"
  log "well-known: http://localhost:${WELL_KNOWN_PORT}/.well-known/matrix/client"
}

cmd_provision() {
  cmd_up

  ensure_admin_user
  wait_for_synapse

  local token
  token="$(matrix_login)"
  ensure_space_and_general_room "${token}"
}

cmd_down() {
  require_cmd docker
  if [[ ! -f "${COMPOSE_FILE}" ]]; then
    die "missing ${COMPOSE_FILE}"
  fi
  if [[ ! -f "${ENV_FILE}" ]]; then
    die "missing ${ENV_FILE} (run: ./scripts/matrix-dev.sh init)"
  fi
  compose down
}

cmd_reset() {
  cmd_down || true
  rm -rf "${MATRIX_DIR}/synapse/data" "${STATE_FILE}"
  log "deleted ${MATRIX_DIR}/synapse/data and ${STATE_FILE}"
}

usage() {
  cat <<EOF
Usage:
  ./scripts/matrix-dev.sh init        # generate local config + secrets (gitignored)
  ./scripts/matrix-dev.sh up          # start Synapse + Element
  ./scripts/matrix-dev.sh provision   # up + ensure admin + create Space + General
  ./scripts/matrix-dev.sh down        # stop stack
  ./scripts/matrix-dev.sh reset       # delete Synapse data (DANGEROUS)
EOF
}

main() {
  local cmd="${1:-}"
  case "${cmd}" in
  init) cmd_init ;;
  up) cmd_up ;;
  provision) cmd_provision ;;
  down) cmd_down ;;
  reset) cmd_reset ;;
  "" | -h | --help) usage ;;
  *) die "unknown command: ${cmd}" ;;
  esac
}

main "$@"
